import { Request } from 'express';
import { Campaign } from './entity/Campaign';
import { Category } from './entity/Category';
import { Image } from './entity/Image';
import { Influencer } from './entity/Influencer';
import { Message } from './entity/Message';
import { User } from './entity/User';
export interface IGetUserAuthInfoRequest extends Request {
    user: User;
    userId: number;
    campaignName: string;
    userBrandName: string;
    campaignCount: number;
    totalRequestCount: number;
    totalAcceptCount: number;
    totalRejectCount: number;
    totalWaitCount: number;
    totalInlfuencerCount: number;
    acceptInlfuencerCount: number;
    waitInlfuencerCount: number;
    rejectInlfuencerCount: number;
    sortOption: string;
    campaignId: number;
    content: string;
    count: number;
    influencer: Influencer;
    messageId: number;
    influencerId: number;
    instagramId: string;
    statusId: number;
    campaign: Campaign;
    campaignOne: Campaign;
    campaignList: Campaign[];
    categoryList: Category[];
    influencerListDown: Influencer[];
    influencerListUp: Influencer[];
    influencerList: Influencer[];
    imageList: Image[];
    messageList: Message[];
    message: Message;
    influencerIdList: Array<number>;
    influencerIdList1: Array<number>;
    influencerIdList2: Array<number>;
}
